layout_spectrum: 0.29836448843295843
typography_spectrum: 0.8737971349723527
color:
  lightness: 0.7980697088511569
  brandColors:
    - '#E6E2AF'
    - '#A7A37E'
    - '#EFECCA'
    - '#046380'
    - '#002F2F'
  saturation: 0.1247528298391896
  brandStrength: 0.6775554177257243
  rhythmicContrast: 0.9371054690674243
coverPrefs:
  filter: false
name: 'Fabio Di Càsola '
analytics: {}
purpose:
  - type: external
    url: 'http://klang.ch'
    label: Klang Festival
  - type: external
    url: 'https://www.zhdk.ch/person/150765'
    label: 'University of Arts, Zürich'
github: true
description: clarinet performer & teacher
author: {}
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
content: []
content_rating:
  adult: false
opengraph: {}
title: Fabio Di Càsola
