name: 'Fabio Di Càsola '
analytics: {}
purpose:
  - type: external
    url: 'http://klang.ch'
    label: Klang Festival
  - type: external
    url: 'https://www.zhdk.ch/person/150765'
    label: 'University of Arts, Zürich'
github: true
description: clarinet performer & teacher
author: {}
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
content: []
layout_spectrum: 0.5082946130291255
color:
  lightness: 0.2685604970278864
  brandColors:
    - '#E6E2AF'
    - '#A7A37E'
    - '#EFECCA'
    - '#046380'
    - '#002F2F'
  saturation: 0.9775878389779072
  brandStrength: 0.9534965240387338
  rhythmicContrast: 0.6826289868458996
content_rating:
  adult: false
typography_spectrum: 0.9311443652438535
opengraph: {}
title: Fabio Di Càsola
coverPrefs:
  filter: false
